- name: Configure Tailscale
  include_role:
    name: artis3n.tailscale
  vars:
    tailscale_args: "--accept-routes=false --advertise-routes={{ subnet_blocks | join(',') }}"
    # Pulled from the env vars on the host running Ansible
    tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_KEY') }}"

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s

- name: Create some basic config
  hosts: localhost
  environment:
    KUBECONFIG: ./kubeconfig.yaml
  roles:
    - metallb_config
