metal:
  children:
    masters:
      hosts:
        metal0:
          {
            ansible_host: 192.168.254.110,
            mac: "18:60:24:22:76:B6",
            disk: sda,
            network_interface: eth0,
          }
        metal1:
          {
            ansible_host: 192.168.254.111,
            mac: "18:60:24:22:4E:94",
            disk: sda,
            network_interface: eno1,
          }
        metal2:
          {
            ansible_host: 192.168.254.112,
            mac: "18:60:24:22:4D:F1",
            disk: sda,
            network_interface: eno1,
          }
        #workers:
        #hosts:
        #metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1}
